---
title: "`r paste0('',params$report_title)`"
subtitle: "`r params$sub_title`"
author: "`r params$author`"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "`r params$abstract`"
output:
  html_document:
    include:
      after_body: after.html
    toc: true
    toc_depth: 5
    toc_float: yes
    toc_collapsed: yes
    number_sections: no
    theme: cerulean
    highlight: zenburn
toc-title: Table of Contents
indent: yes
params:
  report_title: NA
  sub_title: NA
  author: NA
  abstract: NA
  plot_out_line: NA
  title_line_out: NA
  sector_table_dt: NA
  sector_plot_dt: NA
  trending_table_dt: NA
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)

```


<br>

<div class="left" id = "text">
`r params$info`
</div>



```{css ref.label="styles", echo=FALSE}

```


```{css ref.label="pkgdown_styles", echo=FALSE}
```


```{css styles, eval=FALSE, include = FALSE}

/* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 30%;
  padding: 1px;
  height: 150px; /* Should be removed. Only for demonstration */
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

#TOC {
  left: 100px;
  margin: 10px 0px 25px 0px;
  border-color: #184558;
}
/*h1 {
  color: white;
  text-shadow: 2px 2px 4px #000000;
}*/

#text h3{
  color:  #d91e49;
}

.center {
  text-align: center;
}

.blackbox {
   background: #F2F2F2;
   color:  #d91e49;
   margin: 0px;
   width: 400px;
   padding: 5px;
   border: 1px solid  #F2F2F2;
   box-shadow: 0 0 7px rgba(0,0,0,.4);
   border-radius: 15px;
      }

h2#toc-title {
  font-size: 18px;
  padding-left:50px;
  margin: 20px 0px 1px 0px;
}

.main-container {
    margin-left: 30px;
}

.list-group-item.active, .list-group-item.active:hover, .list-group-item.active:focus {
    z-index: 2;
    color: #ffffff;
    background-color: #003b9a;
    border-color: #003b9a;
}

.tocify-subheader > .tocify-item { text-indent: initial; padding-left:2em;}

.author {font-size: 20px;font-family: "American Typewriter", serif;color:#003b9a;font-weight:bold;}
.title {font-family: "American Typewriter", serif; font-size: 25px;font-weight:bold;}
.date {font-family: "American Typewriter", serif; font-size: 17px;font-weight:normal;color:#003b9a;}
.subtitle {font-family: "American Typewriter", serif; font-size: 20px;font-weight:normal;color:#003b9a;}
.abstract {font-size: 14px;font-family: "American Typewriter", serif;color:#465362;font-weight:normal;font-style:italic;}



h1 {font-family: "American Typewriter", serif; font-size: 16px;font-weight:bold;font-style:italic;color:#003b9a;}
h2 {font-family: "American Typewriter", serif; font-size: 14px;font-weight:bold;font-style:italic;color:#003b9a;}
h3 {font-family: "American Typewriter", serif; font-size: 14px;font-weight:bold;font-style:italic;color:#003b9a;}
h4 {font-family: "American Typewriter", serif; font-size: 12px;font-weight:bold;font-style:italic;color:#003b9a;}
h5 {font-family: "American Typewriter", serif; font-size: 18px;font-weight:bold; font-style:italic;color:#003b9a;}
p {font-family: "American Typewriter", serif;font-size: 14px;}



.header {
  border-bottom-color: #555;
  font-size: 1.5rem;
  font-weight: 700;
  /*text-transform: uppercase;*/
  color:#465362; 
}
/* Highlight headers when sorting */
.header:hover,
.header:focus,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #eee;
}

.manufacturer {
  display: flex;
  align-items: center;
}
.manufacturer-logo {
  height: 2rem;
  width: 4rem;
  border: 1px solid #f0f0f0;
}
.manufacturer-name {
  margin-left: 1rem;
  font-size: 1.4rem;
  font-weight: 700;
  color:#465362; 
}
.manufacturer-origin {
  margin-left: 0.35rem;
  color: hsl(0, 0%, 45%);
  font-size: 1.125rem;
  font-weight: 700;
}

a {color:#003b9a;font-weight:normal}

body, td {
   font-size: 14px;
}
code.r{
  font-size: 16px;
}
pre {
  font-size: 16px
}



```


```{css pkgdown_styles, include=FALSE}

/* pkgdown articles */
.row > main {
  max-width: 1800px;
}
.page-header {
  display: none;
}
/* rmarkdown html documents */
.main-container {
  max-width: 1600px !important;
  margin-left: 80px;
  margin-right: 80px;
  color:#184558;
  font-family: "American Typewriter", serif; 
  font-size: 15px;
}
```


```{r results = 'asis', echo = F, warning=FALSE, error=FALSE, message=FALSE,fig.align = "center", fig.width = 8, out.width = "100%", out.height = "90%"}


if(!is.null(params$sector_table_dt)){
  cat("\n## Sectors \n\n")
  cat ("\n\n\n\n\n")
  params$sector_table_dt
}


```




```{r results = 'asis', echo = F,warning=FALSE, error=FALSE, message=FALSE,fig.align = "center", fig.width = 8, out.width = "100%", out.height = "90%"}


if(!is.null(params$sector_plot_dt)){
  cat("\n## Sectors \n\n")
  cat ("\n\n\n\n\n")
  params$sector_plot_dt
}


```



```{r results = 'asis', echo = F, warning=FALSE, error=FALSE, message=FALSE,fig.align = "center", fig.width = 8, out.width = "100%", out.height = "90%"}


if(!is.null(params$trending_table_dt)){
  cat("\n## Trending \n\n")
  cat ("\n\n\n\n\n")
  params$trending_table_dt
}


```





```{r results = 'asis', echo = F, fig.align = "center", fig.width = 8, out.width = "100%", out.height = "90%"}


if(!is.null(params$plot_out_line)){
  cat("\n##", params$title_line_out,"\n\n")
  cat ("\n\n\n\n\n")
  params$plot_out_line
}


```


